@url = 'http://localhost:3333'

GET http://localhost:3333/users

###

POST http://localhost:3333/users

{
  "name": "Alexandre 2",
  "email": "staff@agenciabekor.com"
}

###

PUT http://localhost:3333/users/b9536270-d6ac-4ec3-b337-3552ccf178fa

{
  "name": "Alexandre 3",
  "email": "staff@agenciabekor.com"
}

###
GET http://localhost:3333/notFound

###
DELETE http://localhost:3333/users/b9536270-d6ac-4ec3-b337-3552ccf178fa