GET {{$dotenv BASE_URL}}/transactions

###
GET {{$dotenv BASE_URL}}/transactions/dffa1e47-2c66-4f83-90c7-01c7393a246d

###
GET {{$dotenv BASE_URL}}/transactions/report

###

POST {{$dotenv BASE_URL}}/transactions
Content-Type: application/json

{
 "description": "New register",
 "amount": 12000,
 "type": "credit"
}

###
DELETE {{$dotenv BASE_URL}}/transactions/ba63f1c3-8dd9-4a4f-93b8-c9b6d07cdc38